server:
    interface: 0.0.0.0
    port: 53

    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes

    access-control: 10.42.0.0/24 allow
    access-control: 10.42.1.0/24 allow

    hide-identity: yes
    hide-version: yes

    tls-port: 853
    tls-upstream: yes

forward-zone:
    name: "."
    forward-ssl-upstream: yes
    # OpenDNS servers
    forward-addr: 208.67.222.222@853
    forward-addr: 208.67.220.220@853
