# Interfejsy
interface=br0
interface=lo
bind-interfaces

# DHCP (24h lease time – optymalnie w sieci domowej)
dhcp-range=192.168.32.10,192.168.32.253,24h
dhcp-option=3,192.168.32.1 # brama (router)
dhcp-option=6,192.168.32.1 # DNS = router (dnsmasq)

# Lokalna domena
domain=lan
local=/lan/
expand-hosts

# Nie forwarduj zapytań do domen lokalnych
domain-needed
bogus-priv
stop-dns-rebind

# Forwardowanie tylko do unbound (DoT stub resolver)
server=127.0.0.2
