server:
    module-config: "respip validator iterator"

    # Ustawienia ogólne
    verbosity: 1
    interface: 127.0.0.2
    port: 53
    access-control: 127.0.0.1/32 allow

    do-ip6: no
    hide-identity: yes
    hide-version: yes

    cache-max-ttl: 512
    cache-min-ttl: 16

    # Ustawienia dla DNS-over-TLS
    tls-port: 853
    tls-upstream: yes
    # Adres serwera DNS-over-TLS
    forward-zone:
        name: "."
        forward-ssl-upstream: yes
        forward-addr: 208.67.222.222@853
        forward-addr: 208.67.220.220@853
rpz:
    name: "hagezi.rpz"
    zonefile: "/var/lib/unbound/rpz/hagezi.rpz"
