interface=wlan1
driver=nl80211
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0

ssid=RANDOM_SSID
# Siec ukryta
ignore_broadcast_ssid=1

country_code=PL
ieee80211d=1
# To oznacza uzycie 5GHz
hw_mode=a

ieee80211n=1
ieee80211ac=1
ht_capab=[HT40+][SHORT-GI-20][SHORT-GI-40]
vht_capab=[SHORT-GI-80]
vht_oper_chwidth=1
vht_oper_centr_freq_seg0_idx=42
wmm_enabled=1
channel=44

auth_algs=1
wpa=2
wpa_passphrase=WIFI_PASSWORD
wpa_key_mgmt=WPA-PSK SAE
rsn_pairwise=CCMP
ieee80211w=2

bridge=br0
