interface=wlan0
driver=nl80211
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0

ssid=RANDOM_SSID
country_code=PL
ieee80211d=1
hw_mode=g
channel=6

ieee80211n=1
ht_capab=[HT40+][SHORT-GI-20][SHORT-GI-40][DSSS_CCK-40]
wmm_enabled=1

# w celu ukrycia sieci (opcjonalnie):
ignore_broadcast_ssid=1

auth_algs=1

wpa=2
wpa_passphrase=WIFI_PASSWORD
wpa_key_mgmt=WPA-PSK SAE
rsn_pairwise=CCMP
ieee80211w=2

# Bridge support
bridge=br0
